[project]
name = "odoo-addons-oca-server-env"
version = "17.0.20240108.0"
dependencies = [
    "odoo-addon-server_environment>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
